//HANGMAN GAME
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

public class SEATWORK9F {
        public static void main(String[] args) {

                    String filePath = "words.txt";
                            ArrayList<String> words = new ArrayList<>();

                                    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
                                                    String line;

                                                                while ((line = reader.readLine()) != null) {
                                                                                    if (!line.trim().isEmpty()) {  
                                                                                                            words.add(line.trim().toLowerCase());
                                                                                    }
                                                                }

                                    } catch (IOException e) {
                                                    System.out.println("Error reading file.");
                                                                return; 
                                    }

                                            if (words.isEmpty()) {
                                                            System.out.println("No words found in file.");
                                                                        return;
                                            }

                                                    Random random = new Random();
                                                            String word = words.get(random.nextInt(words.size()));

                                                                    Scanner scanner = new Scanner(System.in);
                                                                            ArrayList<Character> wordState = new ArrayList<>();
                                                                                    ArrayList<Character> guessedLetters = new ArrayList<>(); 
                                                                                            int wrongGuesses = 0;

                                                                                                    for (int i = 0; i < word.length(); i++) {
                                                                                                                    wordState.add('_');
                                                                                                    }

                                                                                                            System.out.println("\n--- WELCOME TO HANGMAN! ---");

                                                                                                                    while (wrongGuesses < 6) {

                                                                                                                                    System.out.println(getHangmanArt(wrongGuesses));

                                                                                                                                                System.out.print("Word: ");
                                                                                                                                                            for (char c : wordState) {
                                                                                                                                                                                System.out.print(c + " ");
                                                                                                                                                            }
                                                                                                                                                                        System.out.println();

                                                                                                                                                                                    System.out.print("Guess a letter: ");

                                                                                                                                                                                                
                                                                                                                                                                                                            String input = scanner.next();
                                                                                                                                                                                                                        if (input.length() != 1 || !Character.isLetter(input.charAt(0))) {
                                                                                                                                                                                                                                            System.out.println("Please enter a single letter.\n");
                                                                                                                                                                                                                                                            continue;
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                    char guess = Character.toLowerCase(input.charAt(0));

                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                            if (guessedLetters.contains(guess)) {
                                                                                                                                                                                                                                                                                System.out.println("You already guessed that letter!\n");
                                                                                                                                                                                                                                                                                                continue;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                        guessedLetters.add(guess);

                                                                                                                                                                                                                                                                                    if (word.indexOf(guess) >= 0) {
                                                                                                                                                                                                                                                                                                        System.out.println("Correct Guess!\n");

                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < word.length(); i++) {
                                                                                                                                                                                                                                                                                                                                                if (word.charAt(i) == guess) {
                                                                                                                                                                                                                                                                                                                                                                            wordState.set(i, guess);
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        if (!wordState.contains('_')) {
                                                                                                                                                                                                                                                                                                                                                                System.out.println(getHangmanArt(wrongGuesses));
                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("You win!");
                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("The word was: " + word);
                                                                                                                                                                                                                                                                                                                                                                                                                            scanner.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                        wrongGuesses++;
                                                                                                                                                                                                                                                                                                                        System.out.println("Wrong Guess!\n");
                                                                                                                                                                                                                                                                                    }
                                                                                                                    }

                                                                                                                            System.out.println(getHangmanArt(wrongGuesses));
                                                                                                                                    System.out.println("Game Over!");
                                                                                                                                            System.out.println("The word was: " + word);

                                                                                                                                                    scanner.close();
        }

            static String getHangmanArt(int wrongGuesses) {
                        return switch (wrongGuesses) {
                                        case 0 -> """
                                                               |
                                                                                    /
                                                                                                          
                                                                                                                                
                                                                                                                                                      
                                                                                                                                                                            """;
                                                                                                                                                                                        case 1 -> """
                                                                                                                                                                                                               |
                                                                                                                                                                                                                                    / o
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                            """;
                                                                                                                                                                                                                                                                                                                                        case 2 -> """
                                                                                                                                                                                                                                                                                                                                                               |
                                                                                                                                                                                                                                                                                                                                                                                    / o
                                                                                                                                                                                                                                                                                                                                                                                                           |
                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             """;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         case 3 -> """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               /|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    / o
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case 4 -> """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   / o
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         /|\\
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           """;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       case 5 -> """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  / o
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /|\\
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          """;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      case 6 -> """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /|
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 / o
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /|\\
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             / \\
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         """;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     default -> "";
                        };
            }

                        }
            }
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                        }
                                                                                                                                                            }
                                                                                                                    }
                                                                                                    }
                                            }
                                    }
                                                                                    }
                                                                }
                                    }
        }
}
